export enum Department {
  GENERAL = 'General',
  CARDIOLOGY = 'Cardiology',
  ORTHOPEDICS = 'Orthopedics',
  PEDIATRICS = 'Pediatrics',
  GYNECOLOGY = 'Gynecology',
  DERMATOLOGY = 'Dermatology',
  NEUROLOGY = 'Neurology',
  RADIOLOGY = 'Radiology',
  LABORATORY = 'Laboratory',
  PHARMACY = 'Pharmacy',
  EMERGENCY = 'Emergency',
  ICU = 'ICU',
  OPERATION_THEATRE = 'Operation Theatre',
  ADMINISTRATION = 'Administration',
}
